version: 0.2
pipeline:
 stages:
  stage1:
    - echo Hello
  stage2:
    phases:
    install:
      commands:
        - "apt install unzip -y"
        - "wget https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip"
        - "unzip terraform_1.1.8_linux_amd64.zip"
        - "mv terraform /usr/bin/"
    pre_build:
      commands:
        - terraform init
        - terraform validate

    build:
      commands:
        - terraform plan -auto-approve

    post_build:
      commands:
        - echo terraform plan completed
